# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         
dist: xenial
os: linux

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

# Instalação de Módulos que são necessários para a Aplicação.                                                                                                                                            
install:                                                                                                                                                                                                 
  - pip install flask flask-wtf

addons:
  sonarcloud:
    organization: lukasborges
    token: ${SONAR_TOKEN}

script:
    - coverage report app.py || travis_terminate 1;
    - coverage xml app.py || travis_terminate 1;
    - sonar-scanner || travis_terminate 1;
    

# Definir o Deploy no Heroku
deploy:
  strategy: api  
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-lucasborges
  on:
      branch: main
